# Generated by Django 5.1 on 2024-08-25 04:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=api.models.generate_radnom_num, editable=False, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('cost', models.FloatField(max_length=10)),
                ('rating', models.FloatField(max_length=5)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
    ]
